### ISSUE TITLE
It would appear that the model subscribe functionality is not needed?

### ISSUE THREAD

**Issue by jeffbski** [gunar/sam-redux#2]
In the model code you have, it would seem that the subscribe functionality is never used, so is this needed for anything?

I commented it out and everything seems to work fine, so I was wondering if that was left over from a refactor or something?

This code appears to be unused:
- https://github.com/gunar/sam-redux/blob/master/src/model.js#L12-L15
- https://github.com/gunar/sam-redux/blob/master/src/model.js#L22-L31
- https://github.com/gunar/sam-redux/blob/master/src/model.js#L34

Am I missing something?

**Comment by gunar** [comment]
Hmm... I guess you're right. If I recall correctly, this is code I had previously used without React, and therefore needed a PubSub system of my own to make the UI react to state changes.

**Comment by zz-james** [comment]
great you posted this, was readiing code thinking 'I'm not sure why this is here'
👍
